### ISSUE TITLE
No LICENSE file defined.

### ISSUE THREAD

**Issue by b3sigma** [jakebian/hypercanvas.js#1]
Your project is pretty cool and I'm sure many people will be interested in using it. However, there is no LICENSE file defined. Would you be willing to open it up via GPL or some other mechanism? It looks like some of your other projects are using GPL. Thanks!

**Comment by jakebian** [comment]
Resolved by https://github.com/jakebian/hypercanvas.js/commit/2e021b5324e2f6774fce5de8634e02b41319312e
